version: "3.7"

services:
  database:
    image: postgres:15.3-alpine3.18
    env_file:
      - ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432

volumes:
  pgdata: