# Generated by Django 3.2 on 2023-05-26 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default=None, max_length=1000, null=True, verbose_name='Картинка уведомления')),
                ('text', models.CharField(max_length=1000, verbose_name='Текст уведомления')),
                ('link', models.CharField(default=None, max_length=1000, null=True, verbose_name='Ссылка')),
                ('type', models.IntegerField(choices=[(0, 'Обновление'), (1, 'Социальное'), (2, 'Важное')], verbose_name='Тип списка')),
                ('action', models.IntegerField(choices=[(1, 'Ссылка'), (2, 'Подтверждение'), (3, 'Комментарий')], default=1, verbose_name='Действие')),
                ('status', models.BooleanField(default=False, verbose_name='Прочитано?')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Увед',
                'verbose_name_plural': 'Уведы',
                'db_table': 'user_notifications',
            },
        ),
    ]
