# Generated by Django 3.2 on 2023-07-12 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_auto_20230709_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermassnotifications',
            old_name='status',
            new_name='read',
        ),
        migrations.RenameField(
            model_name='usernotifications',
            old_name='status',
            new_name='read',
        ),
        migrations.RemoveField(
            model_name='usermassnotifications',
            name='date',
        ),
        migrations.AddField(
            model_name='commentmock',
            name='reply_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.commentmock', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='massnotifications',
            name='action',
            field=models.IntegerField(choices=[(1, 'Глава залита'), (2, 'Глава стала бесплатной'), (3, 'Уведомление сайта')], default=1, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='massnotifications',
            name='type',
            field=models.IntegerField(choices=[(1, 'Обновление'), (2, 'Социальное'), (3, 'Важное')], verbose_name='Тип списка'),
        ),
        migrations.CreateModel(
            name='SpecialOfferMock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нужная сумма')),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Награда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterMock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='Номер главы')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.titlemock', verbose_name='Тайтл')),
            ],
        ),
        migrations.CreateModel(
            name='BillingMock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='BadgeMock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
