# Generated by Django 3.2 on 2023-07-12 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_auto_20230712_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Категория 1'), (2, 'Категория 2'), (3, 'Категория 3')], verbose_name='Вкладка')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.titlemock', verbose_name='Тайтл')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
