# Generated by Django 3.2 on 2023-07-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_titlebookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badgemock',
            options={'verbose_name': 'Бейдж', 'verbose_name_plural': 'Бейджи'},
        ),
        migrations.AlterModelOptions(
            name='billingmock',
            options={'verbose_name': 'Пополнение', 'verbose_name_plural': 'Пополнения'},
        ),
        migrations.AlterModelOptions(
            name='chaptermock',
            options={'verbose_name': 'Глава', 'verbose_name_plural': 'Главы'},
        ),
        migrations.AlterModelOptions(
            name='commentmock',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='massnotifications',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='specialoffermock',
            options={'verbose_name': 'Специльное предложение', 'verbose_name_plural': 'Специальные предложения'},
        ),
        migrations.AlterModelOptions(
            name='titlebookmark',
            options={'verbose_name': 'Вкладка', 'verbose_name_plural': 'Вкладки'},
        ),
        migrations.AlterModelOptions(
            name='titlemock',
            options={'verbose_name': 'Тайтл', 'verbose_name_plural': 'Тайтлы'},
        ),
        migrations.AlterModelOptions(
            name='usermassnotifications',
            options={'verbose_name': 'Рассылка пользователя', 'verbose_name_plural': 'Рассылки пользователю'},
        ),
        migrations.AlterModelOptions(
            name='usernotifications',
            options={'verbose_name': 'Уведомление пользователя', 'verbose_name_plural': 'Уведомления пользователей'},
        ),
        migrations.AlterModelTable(
            name='badgemock',
            table='badges',
        ),
        migrations.AlterModelTable(
            name='billingmock',
            table='billings',
        ),
        migrations.AlterModelTable(
            name='chaptermock',
            table='chapters',
        ),
        migrations.AlterModelTable(
            name='commentmock',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='massnotifications',
            table='mass_notifications',
        ),
        migrations.AlterModelTable(
            name='specialoffermock',
            table='special_offers',
        ),
        migrations.AlterModelTable(
            name='titlebookmark',
            table='title_bookmarks',
        ),
        migrations.AlterModelTable(
            name='titlemock',
            table='titles',
        ),
        migrations.AlterModelTable(
            name='usermassnotifications',
            table='user_mass_notifications',
        ),
    ]
