# Generated by Django 3.2 on 2023-07-12 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20230712_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='massnotifications',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massnotifications',
            name='image',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='Картинка уведомления'),
        ),
        migrations.AddField(
            model_name='massnotifications',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Важный увед?'),
        ),
        migrations.AddField(
            model_name='massnotifications',
            name='link',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='massnotifications',
            name='target_id',
            field=models.BigIntegerField(default=None, null=True, verbose_name='Таргет'),
        ),
        migrations.AddField(
            model_name='massnotifications',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Тайтл'), (2, 'Глава'), (3, 'Комментарий'), (4, 'Пополнение'), (5, 'Специальное предложение'), (6, 'Бейдж')], default=None, null=True, verbose_name='Тип таргета'),
        ),
        migrations.AddField(
            model_name='massnotifications',
            name='text',
            field=models.CharField(default='', max_length=1000, verbose_name='Текст уведомления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='image',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='Картинка уведомления'),
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Важный увед?'),
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='link',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='target_id',
            field=models.BigIntegerField(default=None, null=True, verbose_name='Таргет'),
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Тайтл'), (2, 'Глава'), (3, 'Комментарий'), (4, 'Пополнение'), (5, 'Специальное предложение'), (6, 'Бейдж')], default=None, null=True, verbose_name='Тип таргета'),
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='text',
            field=models.CharField(default='', max_length=1000, verbose_name='Текст уведомления'),
            preserve_default=False,
        ),
    ]
