# Generated by Django 3.2 on 2023-07-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_chaptermock_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст уведомления')),
            ],
            options={
                'verbose_name': 'Текст уведомления',
                'verbose_name_plural': 'Тексты уведомлений',
                'db_table': 'notification_texts',
            },
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='text',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='Текст уведомления'),
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='text_key',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtext', verbose_name='Ключ текста'),
        ),
    ]
