# Generated by Django 3.2 on 2023-07-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_rename_text_key_usernotifications_text_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotifications',
            old_name='text_id',
            new_name='text_key',
        ),
    ]
