# Generated by Django 3.2 on 2023-07-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_rename_text_id_usernotifications_text_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='action',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Действие'),
        ),
    ]
