# Generated by Django 3.2 on 2023-08-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_usernotifications_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massnotifications',
            name='action',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Действие'),
        ),
    ]
