# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rpc.notifications_pb2 as notifications__pb2


class CreateNotificationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateModels = channel.unary_unary(
                '/api.CreateNotifications/CreateModels',
                request_serializer=notifications__pb2.NotificationCreateRequest.SerializeToString,
                response_deserializer=notifications__pb2.NotificationCreateResponse.FromString,
                )


class CreateNotificationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CreateNotificationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateModels': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateModels,
                    request_deserializer=notifications__pb2.NotificationCreateRequest.FromString,
                    response_serializer=notifications__pb2.NotificationCreateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.CreateNotifications', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CreateNotifications(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.CreateNotifications/CreateModels',
            notifications__pb2.NotificationCreateRequest.SerializeToString,
            notifications__pb2.NotificationCreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
