# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifications.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13notifications.proto\x12\x03\x61pi\";\n\x19NotificationCreateRequest\x12\x10\n\x08user_ids\x18\x01 \x03(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\"0\n\x1aNotificationCreateResponse\x12\x12\n\nis_created\x18\x01 \x01(\x08\x32\x66\n\x13\x43reateNotifications\x12O\n\x0c\x43reateModels\x12\x1e.api.NotificationCreateRequest\x1a\x1f.api.NotificationCreateResponseB\x07Z\x05.;apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notifications_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\005.;api'
  _NOTIFICATIONCREATEREQUEST._serialized_start=28
  _NOTIFICATIONCREATEREQUEST._serialized_end=87
  _NOTIFICATIONCREATERESPONSE._serialized_start=89
  _NOTIFICATIONCREATERESPONSE._serialized_end=137
  _CREATENOTIFICATIONS._serialized_start=139
  _CREATENOTIFICATIONS._serialized_end=241
# @@protoc_insertion_point(module_scope)
