MONGODB_HOST = '127.0.0.1'
MONGODB_PORT = 27017
MONGODB_USERNAME = 'admin'
MONGODB_PASSWORD = 'adminpass123'
MONGODB_AUTHSOURCE = 'development'

GRPC_NOTIFICATIONS_SERVICE_HOST = '127.0.0.1'
GRPC_NOTIFICATIONS_SERVICE_PORT = 55000


# formated
MONGODB_AUTHPARAMS = {
    'host': MONGODB_HOST,
    'port': MONGODB_PORT,
    'username': MONGODB_USERNAME,
    'password': MONGODB_PASSWORD,
    'authSource': MONGODB_AUTHSOURCE
}

GRPC_NOTIFICATIONS_SERVICE_CONNECT_LINK = f'{GRPC_NOTIFICATIONS_SERVICE_HOST}:{GRPC_NOTIFICATIONS_SERVICE_PORT}'
